Product listing filter
dev-ashishsethi/R-B-store pull request #2
Opened 2022-02-15 18:35 UTC by dev-ashishsethi

2022-02-16 14:15 UTC, m26unkwn approved these changes
Cross Browser compatibility.

2022-02-16 14:15 UTC, m26unkwn commented on productListing/productListing.css
> +
Everything is looking good to me.
Cross browser compatibility is good. to use.

2022-02-16 16:19 UTC, PuneetP16 approved these changes
Looks good to merge.

2022-02-16 16:19 UTC, PuneetP16 commented on productListing/productListing.html
> +            <input type="text" class=" store-input-box" placeholder="Search the merch" id="email">
Is it a Typo?

2022-02-16 16:26 UTC, dev-ashishsethi commented on productListing/productListing.html
> +            <input type="text" class=" store-input-box" placeholder="Search the merch" id="email">
which line are you referring to?

2022-02-16 17:14 UTC, manojsarna approved these changes
Looks Good!! do check comments

2022-02-16 17:14 UTC, manojsarna commented on app.js
>      "assets\\images\\Anime-silder-1920-1920x450.webp",
check spacing

2022-02-16 17:14 UTC, manojsarna commented on productListing/product.js
> +        secondStar.style.color="#FFD700";
good work , but try to optimize it!!

2022-02-16 17:14 UTC, manojsarna commented on productListing/productListing.css
> +}
need to check if it is a good practice? do check!!

2022-02-16 17:14 UTC, manojsarna commented on productListing/productListing.css
> +}
looks good!!

2022-02-16 17:14 UTC, manojsarna commented on productListing/productListing.css
> +
what this class is refering to?

2022-02-16 17:14 UTC, manojsarna commented on productListing/productListing.css
> +    align-self: center;
looks good!!

2022-02-16 17:14 UTC, manojsarna commented on productListing/productListing.css
> +    margin-top: 1rem;
looks good!!

2022-02-17 08:28 UTC, PuneetP16 commented on productListing/productListing.html
> +            <input type="text" class=" store-input-box" placeholder="Search the merch" id="email">
Line 21, Search the merch.

2022-02-17 08:30 UTC, dipen2000 approved these changes
Looks good to me.

2022-02-17 08:30 UTC, dipen2000 commented on productListing/productListing.css
> +    margin-bottom: 7px;
Use rems

2022-02-17 08:30 UTC, dipen2000 commented on productListing/productListing.css
> +
looks good

2022-02-17 08:30 UTC, dipen2000 commented on productListing/productListing.html
> +                            <strong class="ecommerce-price">₹ 999</strong>
I like that you have used strong tag here to make it semantic, I used p tag for that and that is not semantically correct for this usecase. Looks good.

2022-02-17 08:30 UTC, dipen2000 commented on signIn and SignUp/signUp.html
> +    </footer>
looks good.

2022-02-17 09:20 UTC, muskanbagrecha requested changes
Increase spacing below clear button.

2022-02-17 09:20 UTC, muskanbagrecha commented on productListing/product.js
> +        firstStar.style.color="#FFD700";
Declare color as a variable.

2022-02-17 09:20 UTC, muskanbagrecha commented on productListing/productListing.css
> +    grid-template-areas: "sidebar pr";
rename pr

2022-02-17 09:20 UTC, muskanbagrecha commented on productListing/productListing.css
> +}
add another line break for consistency

2022-02-17 09:20 UTC, muskanbagrecha commented on productListing/productListing.css
> +
remove extra space

2022-02-17 09:20 UTC, muskanbagrecha commented on productListing/productListing.css
> +    padding: 1rem 1rem 1rem 0rem;
Use shorthand properties top right-left bottom

2022-02-17 09:20 UTC, muskanbagrecha commented on productListing/productListing.css
> +.whishlist{
fix spelling

2022-02-17 09:20 UTC, muskanbagrecha commented on productListing/productListing.css
> +    margin: 4rem 0rem 0rem 6rem;
Use shorthand property

2022-02-17 09:20 UTC, muskanbagrecha commented on style.css
>      float: left;
Can use some other alternative to push it to the left as float creates a stacking context

2022-02-17 09:25 UTC, merged