feat: logout
dev-ashishsethi/R-B-store pull request #4
Opened 2022-02-18 19:16 UTC by dev-ashishsethi

2022-02-18 19:22 UTC, ashishkatiyar2404 approved these changes
suggested one thing thn
your code looks good to merge🚀

2022-02-18 19:22 UTC, ashishkatiyar2404 commented on Cart/cart.css
> +#logout{
try to use class variable for styling

2022-02-19 09:20 UTC, pankaj-prog requested changes

2022-02-19 09:20 UTC, pankaj-prog commented on Cart/cart.css
> +
Id has the highest specificity, avoid using it for styling

2022-02-19 09:45 UTC, merged